name: zetproject
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "images/limo.jpg"

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  get: ^4.3.8

  persistent_bottom_nav_bar: ^4.0.2 
  chart_sparkline: ^1.0.5
  shimmer: ^2.0.0
  flutter_spinkit: ^5.1.0
  clippy_flutter: ^1.1.1
  introduction_screen: ^2.1.0
  flutter_datetime_picker: ^1.5.1
  floating_bottom_navigation_bar: ^1.5.2
  convex_bottom_bar: ^3.0.0
  intl: ^0.17.0
  flutter_custom_clippers: ^2.0.0
  expansion_tile_card: ^2.0.0
  page_transition: ^2.0.4
  pie_chart: ^5.0.1
  shared_preferences: ^2.0.7
  bubble: ^1.2.1
  http: ^0.13.1
  chewie: ^1.2.2  
  google_fonts: ^2.1.1
  animate_do: ^2.0.0

  
  
  
flutter:
  assets:
    - images/banner.png
    - images/google.png
    - images/empty.png
    - images/discover.png
    - images/discover2.png
    - images/discover3.png
    - images/logo.jpg
    - images/discover1.png
    - images/chart.jpg
    - images/ask.png
    - images/danadarurat.png
    - images/danapensiun.png
    - images/khabib.jpeg
    - images/nodata.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
    - family: Montserrat
    - family: Nunito

      fonts:
        - asset: fonts/Poppins-Black.otf
        - asset: fonts/Poppins-Bold.otf
          weight: 600
        - asset: fonts/Poppins-Medium.otf
        - asset: fonts/Poppins-Regular.otf
        - asset: fonts/Montserrat-Medium.otf
        - asset: fonts/Montserrat-Light.otf
        - asset: nunito/Nunito-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
